### ISSUE TITLE
about grep

### ISSUE THREAD

**Issue by zhl111** [tadashi-aikawa/obsidian-another-quick-switcher#87] opened 2022-08-19 15:45 UTC
I'm sorry I couldn't find help, but I saw that your site was having the same problem I was having, and I wanted to ask you for help.

 `Windows stdio in console mode does not support writing non-UTF-8 byte sequences`

I encountered this while searching for files using `ripgrep-all`, and I couldn't solve it after a long time of torture ......

**Comment by tadashi-aikawa** [comment] 2022-08-20 06:33
Hi, @zhl111 :)

> Windows stdio in console mode does not support writing non-UTF-8 byte sequences

I have never seen the above error.

> I saw that your site was having the same problem I was having

Would you tell me more details?

**Comment by tadashi-aikawa** [comment] 2022-08-20 12:46
@zhl111 
Thank you for your description.

So your problem is about ripgrep-all and not about my plugin?

**Comment by tadashi-aikawa** [comment] 2022-08-20 14:16
@zhl111 
If your epub file contains non-UTF-8 characters, ripgrep-all doesn't seem support it.

https://github.com/phiresky/ripgrep-all/issues/47

**Comment by tadashi-aikawa** [comment] 2022-08-21 03:46
@zhl111 
Yes. Ah, I have understood why you reached here.

In my case, it occurred when the number of bytes (≈characters) output to the console at one time exceeded a specific value.

If you could share the epub file and steps of reproduction, I might be able to investigate it. (I couldn't reproduce it on my machine.)

**Comment by tadashi-aikawa** [comment] 2022-08-21 03:49
This issue should convert to discussions, so I'll close it.

**Closed as completed** 2022-08-21 03:49 UTC
