### ISSUE TITLE
Bug: cannot show all headers in file

### ISSUE THREAD

**Issue by tkCreate** [tadashi-aikawa/obsidian-another-quick-switcher#68] opened 2022-06-28 03:13 UTC
Cannot show entire headers with the header search in file function, which seems with header number limitation. Hoping the function can be fixed in the future version.
![](https://cloudimg001.oss-cn-shenzhen.aliyuncs.com/image/202206281107793.png)

**Comment by tadashi-aikawa** [comment] 2022-06-28 03:17
Hi, @tkCreate :)

Could you tell me the reproduction procedure? I didn't know what your problem was.

**Comment by tadashi-aikawa** [comment] 2022-06-28 03:26
Hi, @tkCreate. Thank you for your bug report :)

I confirmed that there is the Obsidian's default setting that limits suggestions 100. I'll increase it in the next version 👍

**Comment by tkCreate** [comment] 2022-06-28 03:32
Hi author!  Sorry, I don't know how to describe the reproduction procedure, but there is inconsistence between the header seach result and the outliner content. 
As the issue picture is shown, the outline content is much more than the search result. The content tree cannot be fully shown by header search function.

It is weired from what I have seemed. The cmd function can show all function of obsidian and the plugins' functions. XD

![](https://cloudimg001.oss-cn-shenzhen.aliyuncs.com/image/202206281132243.png)

**Comment by tadashi-aikawa** [comment] 2022-06-28 03:37
Thank you @tkCreate :)

My browser didn't display your screenshots the first time. The next time, I could see them and understood what you wanted 👍 (This is the reason I deleted my first reply to you 😅 )

**Comment by tkCreate** [comment] 2022-06-28 03:38
I have set suggestions to be shown with the maximum limit, which seemed to with no help. 
Thank you for replying the bug report!
![](https://cloudimg001.oss-cn-shenzhen.aliyuncs.com/image/202206281136678.png)

**Comment by tadashi-aikawa** [comment] 2022-06-28 03:48
@tkCreate 
Do you use Obsidian v0.15.3 and BRAT? If you use them, it would be helpful to confirm the next beta version.

**Comment by tkCreate** [comment] 2022-06-28 04:29
currently, I am using the version v0.14.15, and using the lastest version of the plugin.
![](https://cloudimg001.oss-cn-shenzhen.aliyuncs.com/image/202206281228825.png)
![](https://cloudimg001.oss-cn-shenzhen.aliyuncs.com/image/202206281229572.png)

**Comment by tadashi-aikawa** [comment] 2022-06-28 04:36
Thanks. 

Another Quick Switcher v5.x.x supports Obsidian, whose version is more than v0.15.0. So please wait for the official release of Obsidian v0.15 :)

**Comment by tkCreate** [comment] 2022-06-28 04:42
thanks for the advice, I will change it with the lastest official release version. XD

**Comment by tadashi-aikawa** [comment] 2022-06-28 04:48
Fixed in [v5.1.2](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/5.1.2) 🚀

**Closed by tadashi-aikawa** 2022-06-28 04:48 UTC
Labels: bug

**Comment by tkCreate** [comment] 2022-06-28 04:59
Hi author! thanks for such fast repairment, btw how to get the lastest v0.15.0 of obsidian? the latest release is v0.14.15 from the offical release.

**Comment by tadashi-aikawa** [comment] 2022-06-28 06:48
> the latest release is v0.14.15 from the offical release.

Yes, but the latest release of insider version is v0.15.3.

- https://forum.obsidian.md/c/announcements/13
- https://help.obsidian.md/Advanced+topics/Insider+builds
