### ISSUE TITLE
[Feature Request] Open Normal Search at Specific Folder Path

### ISSUE THREAD

**Issue by FelipeRearden** [tadashi-aikawa/obsidian-another-quick-switcher#53] opened 2022-06-17 14:52 UTC
Hello @tadashi-aikawa !!!!!!!!!

My FR is related to open the AQS **at a specific folder path**

📸 Something like this:
![8388816C-CB0F-46FF-8F43-9195AFA6E19E](https://user-images.githubusercontent.com/85180696/174321408-84c4f7eb-640d-4d3c-b67e-f658170ceda5.jpeg)

## My Workflow

My entire vault is folder based. I use [Johnny Decimal](https://johnnydecimal.com) folder strategy to organize the content of my Vault

📸 Folder Structure 
![DA247667-AD5C-40A7-BB4B-8CED46165B93](https://user-images.githubusercontent.com/85180696/174321464-00a0b3ef-933d-4047-9a3f-088dd0604c01.jpeg)

My folder `10 Sources` stores the content that capture from Books, Web Articles, Videos, Podcasts and Twitter

📸 Folder 10 Sources
![63927ADC-4779-407A-A9EA-B0BD51B3F124](https://user-images.githubusercontent.com/85180696/174322453-30a30033-156f-41b6-bcc4-b791b06fc750.jpeg)

To make easier for me to navigate between specific wotkflows/commands for each one of the Sources, I create these QuickAdd Modals with hotkeys `⌘+1,2,3,4,5` to easy access:

📸 Books Commands List
![30A58BB1-2B98-4942-8FB4-636B7FF37C0C](https://user-images.githubusercontent.com/85180696/174321674-6861f52d-5287-41db-bd03-e6b535382ea1.jpeg)

As you can see highlighted, I have a command to open the Books folder `10 Sources/11 Books` 
- This is my FR :) ==> Be able to open AQS Normal Search with `10 Sources/11 Books/` inserted in the text modal :) 

## My FR

Be able to open the AQS Modal at a Specific Folder

1️⃣ My humble idea is to have a section in the settings that lets the user define **relative folder path** that will open AQS with the folde path in the text field:

📸 FR
![EFE437F3-6570-43B6-8E2D-7F02CA57E6E1](https://user-images.githubusercontent.com/85180696/174322094-312cb8e4-a7c0-45f5-8a95-ec0b3b8118bc.jpeg)

2️⃣ Each folder path defined in the settings will be a **Command** form the Command Pallete 

Something that looks like the plugin [Hotkeys for Template](https://github.com/Vinzent03/obsidian-hotkeys-for-specific-files) or [Hotkeys for Specific Files](https://github.com/Vinzent03/obsidian-hotkeys-for-templates)
- Let the user define specific files that can be opened from the command palette.

```
Another Quick Switcher Normal Search at {{folder path}}
```

📸 Hotkeys for Specific Files - Settings
![4B5A2313-06F8-4D8E-9603-AA55A94D4151](https://user-images.githubusercontent.com/85180696/174322211-5f26449c-9fa8-4dad-8f6e-d914f95bad4f.jpeg)

🙏 For users that rely on folders to organize the content in the vault, its very difficult to filter content when you already know folder that the note that you are looking for. 

This would save us a lot of time :)

---

Thanks for reading this !!!!! I hope you like my suggestion 🙏 🙏 🙏

Let me know if you need more information !!!

Have a great day 🌞

**Comment by tadashi-aikawa** [comment] 2022-06-18 05:56
Hi, @FelipeRearden. Thank you for your FR :)

I think your FR is similar to the following issues.

- #19 
- #38 

Do your requirements satisfy if the above two issues are resolved?

**Comment by FelipeRearden** [comment] 2022-06-18 10:36
Hello @tadashi-aikawa !!!!

Thank you for your reply :)

> Do your requirements satisfy if the above two issues are resolved?

@tadashi-aikawa I think my FR has an indirect connection to these two FR. Let me explain :)

├── FR 19
&nbsp;&#160; &nbsp;&#160; └── FR 53 (My FR) 🙏 
&nbsp;&#160; &nbsp;&#160; &nbsp;&#160; &nbsp;&#160;               └──  FR 19 

> * [FR: Suggester that shows only files in the current folder #38](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/issues/38)

FR-38 is about open  the modal at the **active folder path** which could be an feature inside my FR where we could have a variable `{{active_folder_path}}` that could be used to open the normal search modal filtered by the folder path of the active note.  

In other words: in my opinion FR-38 could be a subset of FR-53 (my FR)

> * [[Feature Request] User can create search command with predefined condition #19](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/issues/19)

FR-19 is more complex than my FR. As far as I understand, FR 19 is about apply more filters than just the specific folder path. 

My FR is just about having a way to open the modal filtered by an specific folder path (defined by the user) using an command 
 
In other words: in my opinion FR-53 (my FR)  is a subset of FR-19 

---

**I was waiting for your reply to share some idea 💡** 

### 💡  What if we have a URI scheme for AQS? 

⦿  User defines manually  the folder path that wants to be filtered in AQS Modal; (FR-53)
⦿ An special URI for the active folder  (FR-38)
⦿  Parameter for incremental search (FR-19)

We could use QuickAdd or URI Commands to create hotkeys for these URIs (the same way that we already know how to do for Advanced URI plugin)
- This way AQS doesn’t have to worry about Settings UI and Commands :)


Just an idea :)

Have a great day!

**Comment by tadashi-aikawa** [comment] 2022-06-18 13:44
Thank you for your kind explanation. I agree with you 👍 

Maybe I'll implement these features in the next big release :)

**Comment by FelipeRearden** [comment] 2022-06-18 13:59
> Thank you for your kind explanation. I agree with you 👍 

💙

> Maybe I'll implement these features in the next big release :)

Thank you very much @tadashi-aikawa for considering my FR in future version of AQS :)

I wish you a fantastic day!

**Comment by tadashi-aikawa** [comment] 2022-08-13 15:43
Hi, @FelipeRearden.

Does v6.0.0-beta10 already satisfy your requirements about this issue? I don't have implemented `{{ current folder }}` yet, but it seems the issue is related to #38, not #53.

**Comment by FelipeRearden** [comment] 2022-08-13 16:05
> I don't have implemented `{{ current folder }}` yet, but it seems the issue is related to #38, not #53.

100% agree @tadashi-aikawa !

> Does v6.0.0-beta10 already satisfy your requirements about this issue? 

In my opinion v6.0.0-beta10 satisfy the requirements of my FR :)
- When we get the new version, I will make the test on mobile :)

Thank you very much for making this real. You have no idea how this is important for my workflow and I really liked the way that you implement this feature. 

I have been testing since the first beta and I have been collecting same ideas about this new feature to share with you :)

Have a great day!

**Comment by tadashi-aikawa** [comment] 2022-08-13 16:11
Thank you, @FelipeRearden!

> When we get the new version, I will make the test on mobile :)

If you would test it, it is better with v6.0.0-beta11, which will contain some UI improvements for mobile :)

**Comment by FelipeRearden** [comment] 2022-08-13 16:14
> If you would test it, it is better with v6.0.0-beta11, which will contain some UI improvements for mobile :)

Perfect @tadashi-aikawa !!!!!!!!! Thank you :)

**Comment by FelipeRearden** [comment] 2022-08-14 10:43
Starting Mobile Tests  on iPadOS on v6.0.0-beta-13 ....

**Comment by FelipeRearden** [comment] 2022-08-14 11:39
> Starting Mobile Tests  on iPadOS on v6.0.0-beta-13 .... 

Working perfect on version v6.0.0-beta-13 on Obsidian 1.3.0 on iPadOS 
- After public release, I am gonna migrate to my main vault and start my long process of create a lot search commands from different purposes (Specific Folders and Tags) with different sort priorities.

I let you know if I found something unusual. I think we a have ground breaking new feature :)   

Thank you very much @tadashi-aikawa !!!!!!!

**Comment by tadashi-aikawa** [comment] 2022-08-14 13:28
Thank you very much, @FelipeRearden !! That's good news 😄

**Comment by tadashi-aikawa** [comment] 2022-08-16 09:51
Released in [v6.0.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/6.0.0) 🚀

**Closed by tadashi-aikawa** 2022-08-16 09:51 UTC
Labels: enhancement

**Comment by FelipeRearden** [comment] 2022-08-16 13:19
> Released in [v6.0.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/6.0.0) 🚀

Hello @tadashi-aikawa !!!!

First of all, thank very much for the new version! I am here creating my long lists of Custom Searches :)

I just wanna ask something that **is only happening in mobile** to see if you could take a look :)

### One Question 🧐

The option `Show Directory at new line` is always showing the folder path at a new line even if the option is OFF
ℹ️ This only happens on Mobile;
✅ 100% perfect on Desktop;

I tried to change `flex-direction` on `.another-quick-switcher__item__entry` but I wasn't able to change the pósiton of the Directory(folder path). 

Would you mind taking a look ? maybe is something that is not supported on mobile 

I decide to ask first before opening a new Issue :)

Thanks for everything and have a great day!!!!

**Comment by tadashi-aikawa** [comment] 2022-08-16 13:29
@FelipeRearden 
In mobile, directories are always at a new line because I have considered  **mobile** to be a smartphone (not iPad).

Can you please create a new Issue?
