### ISSUE TITLE
[Feature Request] : Link Search

### ISSUE THREAD

**Issue by avirosso** [tadashi-aikawa/obsidian-another-quick-switcher#45] opened 2022-05-15 04:49 UTC
A 'link search' would be great (like the 'backlink search', but based on the links of the note)

To search/open links from the note to other notes without leaving from keyboard.

Search query could start with ":l "like ":l hoge".

Thanks in advance!

**Comment by tadashi-aikawa** [comment] 2022-05-19 17:19
Hi, @avirosso. Thank you for your FR :)

There is a possibility of implement that. By the way, does [jump to link](https://github.com/mrjackphil/obsidian-jump-to-link) plugin satisfy your desire?

**Comment by avirosso** [comment] 2022-05-19 17:31
Thank you! (Regarding the 'jump to link'-Plugin: I've tested it, but it's too ugly and buggy ;-)

**Comment by tadashi-aikawa** [comment] 2022-05-28 10:25
Sorry for my late answer. OK. 👍

**Comment by Glint-Eye** [comment] 2022-08-08 10:51
Yes that would be a great feature, having both outgoing links and backlinks accessible in one panel. Best would be with a visual indicator, like a seperator between out- and backlinks and maybe option to set what should be shown first.

**Comment by jerviscui** [comment] 2022-11-01 11:44
Hi.

I wan't to know the diffrent betwen Link and BackLink.

1. I created a link search, 
![image](https://user-images.githubusercontent.com/6396748/199223565-8a30862c-4858-40ba-b110-9d5a792d9644.png)
![image](https://user-images.githubusercontent.com/6396748/199225110-bf1dbc2b-05c2-428d-a230-d5c59cffa63b.png)
2. The backlink search not work?
![image](https://user-images.githubusercontent.com/6396748/199225207-1ec3c326-f655-441e-be0e-a2a3cc9808f1.png)

**Comment by jerviscui** [comment] 2022-11-01 11:50
The backlink is the current file's backlink. Am I right?

**Comment by tadashi-aikawa** [comment] 2022-11-01 13:09
@jerviscui 

> The backlink is the current file's backlink. Am I right?

Yes.

> But how do I work with it?

The custom command named `tt` searches markdown files that satisfy at least one of the following conditions.

- case 1:  The markdown file has internal links whose name contains `ripgrep` 
- case 2: The markdown file whose name contains `ripgrep`

In your capture, this is case 2.

**Comment by jerviscui** [comment] 2022-11-03 10:34
> case 1: The markdown file has internal links whose name contains ripgrep

But he didn't retrieve the case 1 file? I understand that two files should be shown, case 1 & case 2.

The file is `Another Quick Switcher Plugin`, and it has internal link `ripgrep`, like this:

```markdown
# Another Quick Switcher Plugin

可以自定义查询范围，文件名、tag、heading、link。
支持使用 [ripgrep](../ripgrep.md) 做正则检索。
```

**Comment by tadashi-aikawa** [comment] 2022-11-03 14:34
@jerviscui 
I see. Another Quick Switcher doesn't show current file as a suggestion. You could show `Another Quick Switcher Plugin.md` if you search in other files.

**Comment by japanese-goblinn** [comment] 2022-11-12 19:38
@tadashi-aikawa sorry, I don't get from this conversation is it possible to search for outgoing links in currently opened file (i.e. markdown links listed in this file)?

**Comment by tadashi-aikawa** [comment] 2022-11-13 07:48
@japanese-goblinn 
No, not yet. It needs to implement this issue 👍

**Comment by japanese-goblinn** [comment] 2022-11-15 22:35
@tadashi-aikawa Oh, great!

**Comment by tadashi-aikawa** [comment] 2022-11-17 02:54
P.S. I'll implement it soon.

**Comment by tadashi-aikawa** [comment] 2022-11-19 15:46
![image](https://user-images.githubusercontent.com/9500018/202859227-4d3fe5f4-5978-4b33-9020-eef810ffc37e.png)

**Comment by Glint-Eye** [comment] 2022-11-19 16:06
> ![image](https://user-images.githubusercontent.com/9500018/202859227-4d3fe5f4-5978-4b33-9020-eef810ffc37e.png)

This is really great. Thx for implementing this! I've been waiting a lot for an intuitive way to navigate through outlinks. It would be really great if the sorting option for this mode supports the order of occurence in the file too (preferrably with an exclusion of duplicates). This would be especially handy for navigating through MOC / Index Files. Thx again for implementing this :)

**Comment by avirosso** [comment] 2022-11-19 16:14
This looks very promising! Thanks!

**Comment by tadashi-aikawa** [comment] 2022-11-20 05:18
Thank you for your quick responses, @Glint-Eye, @avirosso 👍 

I have implemented this feature and updated mp4.

https://user-images.githubusercontent.com/9500018/202886779-c9716f49-20e6-40f1-acfc-eabd0f375eab.mp4

![2022-11-20_14h16_02](https://user-images.githubusercontent.com/9500018/202886902-ffd95c04-08ea-4fc0-be98-fc54dcc3330d.png)

If you are OK, I'll release it in the v7.5.0 release.

**Comment by avirosso** [comment] 2022-11-20 06:08
This would be perfect for me. Thanks a lot!

**Comment by Glint-Eye** [comment] 2022-11-20 08:39
wonderful. thx a lot! :)

**Comment by tadashi-aikawa** [comment] 2022-11-20 10:12
Cool 👍 

And I realized that `open all in new tabs` with "Link search" is very useful for me.. 😄 

https://user-images.githubusercontent.com/9500018/202896310-b29f35df-ffe0-4b5c-98a5-260f87e13f42.mp4

**Comment by tadashi-aikawa** [comment] 2022-11-20 14:36
Released in [v7.5.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/7.5.0) 🚀

**Closed by tadashi-aikawa** 2022-11-20 14:36 UTC
Labels: enhancement

**Comment by avirosso** [comment] 2022-11-20 14:57
Hi, I've tested it, but unfortunately the result list is always empty. 

Maybe your plugin only searches/finds wikilinks `[[link]]` not real markdown-links `[text](link)` ?

Obsidian is a markdown editor, so I (and many others too) always use real markown links (according to the markdown specification) for full compatibility ...

Any idea/help?

Thanks

**Comment by tadashi-aikawa** [comment] 2022-11-20 15:32
@avirosso 
I couldn't reproduce your situation. Could you tell me the reproduction steps?

https://user-images.githubusercontent.com/9500018/202910863-fe682ae2-cfce-4be2-8bca-06d26ba860f3.mp4

**Comment by avirosso** [comment] 2022-11-20 16:39
Thanks for your quick response!

After several tests: The problem is not wikilinks vs markdown-links (sorry).

It's seems to be a 'path' problem: In "Obsidian Settings > Link > Files & Links > Link format" I use "Shortest path when possible". So by default there are no 'paths' in the markdown-links (because my files are in folders but the filenames are unique in the vault).

The outgoing-link-search only works (shows results) for links with the full path.

Works: 
`[Ludwig Wittgenstein](03%20Notizen/Ludwig%20Wittgenstein.md)`

Doesn't work: 
`[Ludwig Wittgenstein](Ludwig%20Wittgenstein.md)`

**Comment by tadashi-aikawa** [comment] 2022-11-21 01:39
Thanks, @avirosso.

Continue to https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/issues/127#issue-1457150705 👍

**Comment by tadashi-aikawa** [comment] 2022-11-21 02:11
@avirosso 
Fixed in [v7.5.1](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/7.5.1) 🚀

**Comment by avirosso** [comment] 2022-11-21 03:41
With 7.5.1 it works - thank you very much for this immediate fix!

And by the way: Thanks for this great plugin! I've  installed over 70 plugin - your plugin is the one I use the most often (a hundred times a day) - very powerful!

**Comment by japanese-goblinn** [comment] 2022-11-21 20:50
@tadashi-aikawa i'm glad that to have this feature now, super helpful, thanks
