### ISSUE TITLE
Error starting up switcher since 5.0.3

### ISSUE THREAD

**Issue by torstenkoepke** [tadashi-aikawa/obsidian-another-quick-switcher#59] opened 2022-06-21 10:22 UTC
I am getting this error with the current Obsidian insider and switcher version 5.0.3.

Before the latest switcher update the switcher worked like expected. 

plugin:obsidian-another-quick-switcher:291 Uncaught Error: Unexpected error: newFileLocation is invalid
    at AppHelper.getPathToBeCreated (plugin:obsidian-another-quick-switcher:291:23)
    at AppHelper.createPhantomFile (plugin:obsidian-another-quick-switcher:296:31)
    at eval (plugin:obsidian-another-quick-switcher:243:124)
    at Array.map (<anonymous>)
    at AppHelper.searchPhantomFiles (plugin:obsidian-another-quick-switcher:243:108)
    at new AnotherQuickSwitcherModal (plugin:obsidian-another-quick-switcher:940:30)
    at showSearchDialog (plugin:obsidian-another-quick-switcher:1527:19)
    at Object.checkCallback (plugin:obsidian-another-quick-switcher:1586:17)
    at hH (app.js:1:1662800)
    at t.onChooseItem (app.js:1:1708934)

**Comment by tadashi-aikawa** [comment] 2022-06-21 10:27
Hi, @torstenkoepke. Thank you for your bug report :)

Could you tell me the output of `app.vault.config.newFileLocation` in devtools?

![image](https://user-images.githubusercontent.com/9500018/174778509-49d96eff-c442-437a-84aa-5336d94c7235.png)

**Comment by tadashi-aikawa** [comment] 2022-06-21 10:38
Ah... I have found the cause. I'll fix and release soon.

**Comment by torstenkoepke** [comment] 2022-06-21 10:39
Thanks a lot @tadashi-aikawa for the very fast response and action!

**Comment by tadashi-aikawa** [comment] 2022-06-21 10:44
@torstenkoepke 
Fixed in [v5.0.4](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/5.0.4) 🚀 

Please confirm it 😄

**Comment by torstenkoepke** [comment] 2022-06-21 10:49
From bug to applied fix in 21 mins - congrats @tadashi-aikawa !

**Closed** 2022-06-21 10:50 UTC
Labels: bug
